# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        name: Build
        script:
          - npm install && npm run build
        artifacts:
          - build/**

    - step:
        name: Deploy to Firebase
        deployment: production
        script:
          - pipe: atlassian/firebase-deploy:0.2.1
            variables:
              FIREBASE_TOKEN: 1/WBo-RPIY0tGm4blG-_3_d0cqO1NqkTo6wcJY7YYehRCIOXr6hyMnoUNvEbnSXybx
              PROJECT_ID: diversityhack